# Generated by Django 5.1.6 on 2025-04-10 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_birthday_customuser_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='provider_requested',
            field=models.BooleanField(default=False),
        ),
    ]
